Repository ro-ll-bot/survey-generator, pull requests merged in 2021-01, with the labels that each got.

#11 survey timeline updated
  .gitignore
  debug.log
  src/app/TimeLine.tsx
  src/components/survey/Survey.tsx
  src/components/survey/_survey.scss
  src/css/main.css
  src/css/main.css.map
  src/mockSurveyData.json
Labels: enhancement

#12 added navBar Component.
  .gitignore
  .vscode/launch.json
  debug.log
  src/components/navbar/Navbar.tsx
  src/components/navbar/_navbar.scss
  src/css/main.css
  src/css/main.css.map
  src/ui/style/main.scss
Labels: enhancement

#13 React Router Dom implementation
  .vscode/launch.json
  package-lock.json
  package.json
  src/app/Timeline.tsx
  src/app/home/Home.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/_navbar.scss
  src/components/survey/Survey.tsx
  src/components/survey/utils/SurveyConstants.ts
  src/css/main.css
  src/css/main.css.map
  src/index.tsx
Labels: enhancement

#14 Improvement/survey create
  .gitignore
  debug.log
  package-lock.json
  package.json
  requirements.txt
  src/components/choice/Choice.ts
  src/components/choice/Choice.tsx
  src/components/choice/CreateChoice.tsx
  src/components/choice/_choices.scss
  src/components/navbar/_navbar.scss
  src/components/question/CreateQuestion.tsx
  src/components/question/Question.ts
  src/components/question/Question.tsx
  src/components/question/_question.scss
  src/components/survey/Survey.tsx
  src/css/main.css
  src/css/main.css.map
  src/ui/style/_button.scss
  src/ui/style/main.scss
Labels: enhancement, help wanted

#17 Solve conflict
  .gitignore
  debug.log
  src/components/choice/ListChoice.tsx
  src/components/choice/_choices.scss
  src/components/question/ListQuestion.tsx
  src/components/question/_question.scss
  src/components/survey/Survey.tsx
  src/components/survey/_survey.scss
  src/css/main.css
  src/css/main.css.map
  src/mockQuestionData.json
  src/ui/style/_mixins.scss
  src/ui/style/main.scss
Labels: enhancement

#16 Create Result UI created
  src/app/Timeline.tsx
  src/components/navbar/Navbar.tsx
  src/components/result/CreateResult.tsx
  src/components/result/Result.ts
  src/components/result/_result.scss
  src/components/survey/Survey.tsx
  src/css/main.css
  src/css/main.css.map
  src/ui/style/main.scss
Labels: work in progress

#19 Feature/timeline survey card generator
  src/components/survey/Survey.tsx
  src/components/survey/_survey.scss
  src/mockSurveyData.json
Labels: enhancement
